apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
data:
  config.yaml: |
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095
    ingester:
      lifecycler:
        address: "0.0.0.0:9094"
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 5m
      max_chunk_age: 1h
      chunk_target_size: 1048576
      chunk_retain_period: 30s
      max_transfer_retries: 0
      rate_limiter:
        enable: false
      storage:
        trace:
          backend: memory
    compactor:
      compaction:
        compaction_window: 30m
      shared_store:
        type: filesystem
        filesystem:
          directory: /data/tempo-compact
      memcached:
        endpoint: localhost:11211
      ring:
        kvstore:
          store: inmemory
        replication_factor: 1
    limits_config:
      reject_old_samples: true
      ingestion_rate_mb: 1024
      ingestion_burst_size_mb: 4096
