apiVersion: v1
kind: Service
metadata:
  name: loki
  labels:
    app: loki
spec:
  ports:
    - port: 3100
      targetPort: http
      name: http
  selector:
    app: loki
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:latest
          args:
            - "-config.file=/etc/loki/local-config.yaml"
            - "-target=local"
          ports:
            - containerPort: 3100
              name: http
          volumeMounts:
            - name: loki-storage
              mountPath: /etc/loki
          env:
            - name: LOKI_PASSWORD_SECRET
              valueFrom:
                secretKeyRef:
                  name: loki-secret
                  key: password
            - name: LOKI_USERNAME
              value: loki
      volumes:
        - name: loki-storage
          emptyDir: {}
